languageCode = "en-us"
title = "Containerum Docs"
# pygmentsStyle = "monokai"
pygmentsUseClassic = true
pygmentsStyle = "monokai"

[params]
  github = "https://github.com/containerum/containerum-docs"
  issue = "Issue with"


[[menu.docs]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"

[[menu.docs]]
  name = "Installation"
  weight = 2
  identifier = "kube-installation"
  url = "/installation/"

[[menu.docs]]
  name = "Plugins"
  weight = 3
  identifier = "plugins"
  url = "/plugins/"

[[menu.docs]]
  name = "Release Notes"
  weight = 4
  identifier = "release-notes"
  url = "/release-notes/"

[[menu.docs]]
  name = "FAQ"
  weight = 5
  identifier = "faq"
  url = "/faq/"

[[menu.docs]]
  name = "Contribute"
  weight = 6
  identifier = "contribute"
  url = "/contribute/"

[[menu.docs]]
  name = "Installation"
  weight = 7
  identifier = "installation"
  parent = "kube-installation"
  url = "/installation/installation/"
